# Generated by Django 3.1.2 on 2020-11-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('roll', models.IntegerField()),
                ('phone_no', models.IntegerField()),
                ('father_name', models.CharField(max_length=70)),
                ('mother_name', models.CharField(max_length=70)),
                ('father_phone', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.IntegerField()),
                ('shift', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=2)),
                ('students', models.ManyToManyField(to='student.Student')),
            ],
        ),
    ]
